import "dotenv/config";
import "reflect-metadata";

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

import { NestFactory } from "@nestjs/core";
import { FastifyAdapter, type NestFastifyApplication } from "@nestjs/platform-fastify";
import { dump } from "js-yaml";

import { AppModule } from "../app.module";
import { buildOpenApiDocument } from "./setup";

// API First bonus (FR-API-01) — found live: docs/openapi.yaml was a
// hand-written design-time draft ("once Phase 0 scaffolding lands" per
// API-DESIGN.md, which never actually happened), while the real,
// always-accurate spec only ever existed live at GET /api/v1/docs-json —
// generated straight from the controllers themselves via
// buildOpenApiDocument (setup.ts), so it can't drift from what the API
// actually does the way a hand-maintained file can. This script is that
// promised automation: build the exact same document the live server
// serves, without needing a listening HTTP server, and write it to the
// committed file.
//
// Run via `pnpm --filter api run openapi:export`, never `tsx
// src/openapi/export.ts` directly — that npm script runs `nest build`
// first and executes the compiled dist/openapi/export.js on purpose:
// @nestjs/swagger's parameter-metadata explorer depends on decorator
// metadata the Nest CLI's own swagger plugin (nest-cli.json) attaches
// during a real `nest build`, which tsx's on-the-fly transpilation never
// runs. Found live, as a crash inside @nestjs/swagger itself, not an
// error in this file.
//
// CI does not run this automatically — a forgotten regeneration produces
// a stale committed file, not a stale live API; the live spec at
// /docs-json is always correct regardless of whether anyone remembered to
// re-run this.
async function main() {
  const app = await NestFactory.create<NestFastifyApplication>(AppModule, new FastifyAdapter(), {
    logger: false,
  });
  // Found live: without this, SwaggerModule.createDocument builds paths
  // with no prefix (e.g. "/health") while annotateRequiredAccess looks
  // them up as "/api/v1/health" (globalPrefix baked into every lookup) —
  // every annotation silently missed, and the exported paths wouldn't
  // even match what a real client actually calls. main.ts sets this
  // before setupOpenApi for the exact same reason; this script has to
  // match that sequence exactly since it's building the same document.
  app.setGlobalPrefix("api/v1");
  const document = buildOpenApiDocument(app, "api/v1");
  await app.close();

  const outPath = resolve(__dirname, "../../../../docs/openapi.yaml");
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(
    outPath,
    "# Generated by `pnpm --filter api run openapi:export` — do not hand-edit.\n" +
      "# Source of truth is the live server (GET /api/v1/docs-json); this file is a\n" +
      "# committed, reviewable snapshot of it, not a separately-maintained draft.\n" +
      dump(document, { noRefs: true, lineWidth: 100 }),
  );
  // eslint-disable-next-line no-console
  console.log(`Wrote ${Object.keys(document.paths).length} paths to ${outPath}`);
}

main().catch((err) => {
  // eslint-disable-next-line no-console
  console.error(err);
  process.exit(1);
});
